### ISSUE TITLE
[BUG] Duplicate NFTs in the NFT Tab

### ISSUE THREAD

**Issue by lmcmz** [Outblock/Lilico-extension-issue-board#1]
**Describe the bug**
The same NFT showed multiple time in the NFT grid mode

**To Reproduce**
1. Open the app
2. Go to NFT Tab

**Expected behavior**
The same NFT only show once

**Screenshots**
<img width="383" alt="Screen Shot 2022-03-30 at 10 55 33 am" src="https://user-images.githubusercontent.com/9669733/160724841-968d30e7-12b5-4bdc-9b7a-9a1d1c295fb4.png">

**Additional context**
Need use unique key to remove those duplicate NFTs

**Comment by meilixiaozhang** [comment]
<img width="769" alt="Screen Shot 2022-03-30 at 11 05 21" src="https://user-images.githubusercontent.com/41104185/160726829-13a49527-d5eb-42d2-aac4-d861e15856f9.png">
<img width="771" alt="Screen Shot 2022-03-30 at 11 05 31" src="https://user-images.githubusercontent.com/41104185/160726838-ccde7d16-dde1-454a-8fda-36bf3fd0b673.png">

**Comment by lmcmz** [comment]
We need use `contractAddress + tokenId` as identity, and also change the key value in the Grid list

**Comment by meilixiaozhang** [comment]
PR opened for the fix

**Comment by lmcmz** [comment]
Verified the fix in `v0.0.2-alpha` version :)
