### ISSUE TITLE
[BUG] Activity use wrong network data

### ISSUE THREAD

**Issue by lmcmz** [Outblock/Lilico-extension-issue-board#2]
**Describe the bug**
When switch to main network, the transaction activity still use the testnet record.

**To Reproduce**
1. Go to activity tab
2. switch network

**Expected behavior**
The transaction should use the one from current network

**Screenshots**
![Screen Shot 2022-03-30 at 11 47 41 am](https://user-images.githubusercontent.com/9669733/160729335-60d0b80c-7835-422b-8132-8834e31f6d44.png)

**Comment by zzggo** [comment]
Pushed a fix

**Comment by lmcmz** [comment]
Verified the fix in `v0.0.2-alpha` version
