### ISSUE TITLE
[BUG] No loading status for activity tab

### ISSUE THREAD

**Issue by lmcmz** [Outblock/Lilico-extension-issue-board#3]
**Describe the bug**
In the first time, the activity won't loaded and no loading state.

**To Reproduce**
1. Go to activity tab
2. No loading, no result
3. only next time, come again
4. it show all transaction records

**Expected behavior**
It should have a loading status, when it fetch the network

**Screenshots**
![Screen Shot 2022-03-30 at 11 52 00 am](https://user-images.githubusercontent.com/9669733/160729535-f6f442f4-7d05-4ccc-a086-4cbd7644128a.png)

**Comment by john990** [comment]
It seems that all pages are flickering (need to look carefully, the flickering is not obvious), and some pages have an extra line at the bottom.

https://user-images.githubusercontent.com/5292685/160733974-661dfe4a-27f9-4240-b52a-cf04ecaae1e1.mov

**Comment by zzggo** [comment]
fixed

**Comment by lmcmz** [comment]
Verified the fix in `v0.0.2-alpha` version
